# Generated by Django 4.0.6 on 2022-10-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_alter_community_options_remove_community_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='c_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='communityusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='communityadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
