# Generated by Django 4.0.6 on 2022-10-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_c_users_alter_community_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='c_users',
            new_name='users',
        ),
    ]
