# Generated by Django 4.0.6 on 2022-10-30 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(related_name='communityusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
