# Generated by Django 4.0.6 on 2022-10-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='admin',
            new_name='channel_admin',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='admin',
            new_name='community_admin',
        ),
    ]
