# Generated by Django 4.0.6 on 2022-10-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_rename_admin_channels_channel_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='channelcommunity', to='community.community', to_field='community_name'),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
