# Generated by Django 4.0.7 on 2022-10-31 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_alter_channels_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='channelusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='communityusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
