# Generated by Django 4.0.7 on 2022-10-31 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0009_alter_channels_users_alter_community_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
