# Generated by Django 4.0.7 on 2022-10-31 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0010_alter_community_community_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channeladmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channels',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelcommunity', to='community.community', to_field='community_name'),
        ),
    ]
