# Generated by Django 4.0.6 on 2022-11-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_channels_channel_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
