# Generated by Django 4.0.6 on 2022-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_channels_approved_community_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, upload_to='communityicons'),
        ),
        migrations.AddField(
            model_name='community',
            name='poster',
            field=models.ImageField(blank=True, upload_to='communitypics'),
        ),
    ]
