# Generated by Django 4.0.1 on 2022-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_chats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(editable=False),
        ),
    ]
