# Generated by Django 4.0.1 on 2022-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_chats_options_alter_chats_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
