# Generated by Django 4.0.1 on 2022-12-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_chats_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='user_name',
        ),
    ]
