# Generated by Django 4.0.6 on 2022-09-05 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
